# Descriptive Statistics

This section includes the relevant tables for the descriptive statistics section

In [1]:
#import packages
import pandas as pd
import numpy as np

In [2]:
#import the csv before interpolation
df_valais = pd.read_csv('../../data/filtered/merged_valais.csv')
df_valais

,station,time,precip,moisture,pression,temperature,North,East,name,east,north,altitude,Canton
0,VSANZ,201901010000,0.0,NaN,NaN,NaN,NaN,NaN,Anzère,597607,128205,1614,VS
1,VSANZ,201901010010,0.0,NaN,NaN,NaN,NaN,NaN,Anzère,597607,128205,1614,VS
2,VSANZ,201901010020,0.0,NaN,NaN,NaN,NaN,NaN,Anzère,597607,128205,1614,VS
3,VSANZ,201901010030,0.0,NaN,NaN,NaN,NaN,NaN,Anzère,597607,128205,1614,VS
4,VSANZ,201901010040,0.0,NaN,NaN,NaN,NaN,NaN,Anzère,597607,128205,1614,VS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12621307,ZER,202312312310,0.0,95.0,1010.1,-2.0,2.45,2.45,Zermatt,624298,97574,1638,VS
12621308,ZER,202312312320,0.0,92.7,1010.4,-2.1,2.08,1.56,Zermatt,624298,97574,1638,VS
12621309,ZER,202312312330,0.0,94.1,1010.5,-2.0,1.92,1.44,Zermatt,624298,97574,1638,VS
12621310,ZER,202312312340,0.0,94.2,1010.5,-2.1,2.00,1.50,Zermatt,624298,97574,1638,VS
12621311,ZER,202312312350,0.0,94.9,1010.5,-2.2,2.08,1.56,Zermatt,624298,97574,1638,VS

In [ ]:
#rename and change wind stuff
df_valais['wind_speed'] = np.sqrt(df_valais['East']**2 + df_valais['North']**2)

df_valais['direction_rad'] = np.arctan2(-df_valais['East'], -df_valais['North'])
df_valais['wind_direction'] = (np.rad2deg(df_valais['direction_rad']) + 360) % 360

In [30]:
#get the mean wind direction using average vectors
mean_north = df_valais['North'].mean()
mean_east = df_valais['East'].mean()

mean_direction_rad = np.arctan2(-mean_east, -mean_north)
mean_direction = (np.rad2deg(mean_direction_rad) + 360) % 360
print(mean_north, mean_east, mean_direction)

0.19341034681244865 -0.13991234095328767 144.11815970223142

In [18]:
#mean speed
np.sqrt(mean_east**2 + mean_north**2)

np.float64(0.2387111757022295)

In [25]:
latex = (df_valais[['precip', 'moisture', 'pression', 'temperature', 'North', 'East', 'altitude']]
            .describe()
            .drop('count')
            .rename(columns={"precip":"P", 'moisture':"H", 'pression':"pr", 'temperature':"T", 'North':'V', 'East':'U', 'altitude':'z'}) )
print(latex.to_latex(index=True, caption="Descriptive Statistics", label="tab:desc_table", float_format='%.2f'))

\begin{table}
\caption{Descriptive Statistics}
\label{tab:desc_table}
\begin{tabular}{lrrrrrrr}
\toprule
 & P & H & pr & T & V & U & z \\
\midrule
mean & 0.02 & 69.00 & 1018.37 & 7.96 & 0.19 & -0.14 & 1464.23 \\
std & 0.12 & 20.83 & 8.24 & 8.43 & 1.87 & 2.19 & 498.39 \\
min & 0.00 & 4.40 & 976.70 & -24.70 & -17.80 & -20.20 & 461.00 \\
25% & 0.00 & 52.80 & 1014.00 & 1.60 & -0.60 & -0.88 & 1204.25 \\
50% & 0.00 & 70.70 & 1019.30 & 7.60 & 0.09 & 0.00 & 1536.50 \\
75% & 0.00 & 87.60 & 1023.90 & 13.90 & 0.88 & 0.80 & 1849.50 \\
max & 44.60 & 100.00 & 1044.90 & 38.00 & 17.50 & 14.60 & 2300.00 \\
\bottomrule
\end{tabular}
\end{table}

In [12]:
#get lowest humidty data points
table = df_valais[df_valais['moisture']==100].groupby('station').count().sort_values('moisture', ascending=True)
print(table['moisture'].to_latex(index=True, caption="Table indicating the total amount of 10-minute intervals where humidity reached 100 percent", label="tab:100moisture"))

\begin{table}
\caption{Table indicating the total amount of 10-minute intervals where humidity reached 100 percent}
\label{tab:100moisture}
\begin{tabular}{lr}
\toprule
 & moisture \\
station &  \\
\midrule
EVI & 13 \\
SIO & 384 \\
MOB & 879 \\
ZER & 971 \\
VIS & 1267 \\
ULR & 1963 \\
MVE & 2803 \\
EVO & 3880 \\
MAR & 5114 \\
GRC & 8965 \\
\bottomrule
\end{tabular}
\end{table}